"use client";
import {useEffect,useState} from "react";
import {ACTIVITY,type Activity} from "@/lib/webmcp/activity";
import {context,register} from "@/lib/webmcp/register";
import {names,schemas,run,type Name} from "@/lib/webmcp/tools";
export default function ResearchPanel(){
 const [status,setStatus]=useState("Initializing"),[registered,setRegistered]=useState<Name[]>([]),[logs,setLogs]=useState<Activity[]>([]),[name,setName]=useState<Name>("search_articles"),[input,setInput]=useState('{"query":"GPU memory","limit":3}'),[result,setResult]=useState(""),[open,setOpen]=useState(false),[mode,setMode]=useState("local harness");
 useEffect(()=>{const controller=new AbortController();const ctx=context();if(!ctx){setStatus("Unavailable");return;} register(ctx,controller.signal,n=>setRegistered(r=>[...r,n])).then(()=>{if(!controller.signal.aborted)setStatus("Registered");}).catch(e=>{controller.abort();setRegistered([]);setStatus("Registration failed: "+String(e));});return()=>controller.abort();},[]);
 useEffect(()=>{if(!open)return;const listener=(e:Event)=>setLogs(l=>[...l,(e as CustomEvent<Activity>).detail].slice(-100));window.addEventListener(ACTIVITY,listener);return()=>window.removeEventListener(ACTIVITY,listener);},[open]);
 async function execute(){try{const args=JSON.parse(input);if(mode === "native"){const ctx=context();if(!ctx?.getTools||!ctx.executeTool)throw new Error("Native discovery/execution unavailable");const tool=(await ctx.getTools()).find(t=>t.name===name);if(!tool)throw new Error("Tool not discovered");const raw=await ctx.executeTool(tool,args);setResult(JSON.stringify(JSON.parse(raw),null,2));}else setResult(JSON.stringify(await run(name,args,"local harness"),null,2));}catch(e){setResult(String(e));}}
 return <details className="webmcpPanel" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Agent-native web · research mode</summary><p>Experimental WebMCP · evolving community-group draft, not a W3C Standard or on the Standards Track.</p><p role="status">Native status: {status}. Registered: {registered.join(", ")||"none"}</p><p>DOM → inferred capabilities · WebMCP → declared capabilities. Tools read real CUDA/Inference Atlas content. Calls may highlight temporary UI state. No backend or remote telemetry.</p><label>Execution mode <select value={mode} onChange={e=>setMode(e.target.value)}><option>local harness</option><option value="native">native</option></select></label><p>Local harness verifies application logic; it does not demonstrate native discovery or a browser agent.</p><label>Tool <select value={name} onChange={e=>{const n=e.target.value as Name;setName(n);setInput(n === "search_articles"?'{"query":"GPU memory","limit":3}':n === "get_article"?'{"id":"cuda:atlas:sms"}':'{"id":"cuda:atlas:sms","format":"APA"}');}}>{names.map(n=><option key={n}>{n}</option>)}</select></label><details><summary>Input schema</summary><pre>{JSON.stringify(schemas[name],null,2)}</pre></details><label>JSON arguments<textarea value={input} onChange={e=>setInput(e.target.value)} rows={4}/></label><button onClick={execute}>Execute</button><pre aria-live="polite">{result}</pre><p>Local log: last 100 calls while this panel is open. Inputs may contain personal text; review before sharing.</p><button onClick={()=>setLogs([])}>Clear log</button> <button onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(logs,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="webmcp-local-log.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}>Export log</button><pre>{JSON.stringify(logs,null,2)}</pre></details>;
}
